name: Deploy public site to web.commonapproach.org

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["public-prep"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow access to the repository
# contents (write allows creating a release)
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Deploy
        run: source $GITHUB_WORKSPACE/.github/workflows/deploy.sh
        env:
          # This section sets up the environment used by the
          # deploy script. These values are injected from
          # the repo's secret store
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_DOCROOT: ${{ secrets.SSH_DOCROOT }}
